name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"  # daily at 06:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}      # your secret with repo + read:user + user:email
          user: soovittt
          template: classic
          base: header, activity, community, repositories, metadata
          config_animated: yes
          config_timezone: America/Los_Angeles
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
